# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: korobokvk/data-generator
    docker:
      # specify the version you desire here
      - image: circleci/buildpack-deps:stretch

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
    publish-latest:
      environment:
        IMAGE_NAME: data-generator
      docker:
        - image: circleci/buildpack-deps:stretch
      steps:
        - setup_remote_docker
        - run:
            name: Publish Docker Image to Docker Hub
            command: |
              docker login --username "$DOCKER_USER" --password "$DOCKER_PASS" | sudo docker push  $IMAGE_NAME:latest
  
  workflows:
    version: 2
    build-master:
      jobs:
        - build:
            filters:
              branches:
                only: master
        - publish-latest:
            requires:
              - build
            filters:
              branches:
                only: master
